# Generated by Django 5.2 on 2025-04-24 06:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='exports/')),
                ('map_type', models.CharField(choices=[('PNG', 'PNG'), ('SVG', 'SVG')], max_length=50)),
                ('level', models.CharField(choices=[('SURFACE', 'Surface'), ('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], max_length=10)),
                ('observation_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Isobar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(help_text='Pressure in hPa')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('level', models.CharField(choices=[('SURFACE', 'Surface'), ('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], max_length=10)),
                ('observation_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Isotherm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('level', models.CharField(choices=[('SURFACE', 'Surface'), ('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], max_length=10)),
                ('observation_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PressureCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_type', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low')], max_length=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('pressure', models.FloatField(help_text='Pressure in hPa')),
                ('level', models.CharField(choices=[('SURFACE', 'Surface'), ('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], max_length=10)),
                ('observation_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('station_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('elevation', models.FloatField(help_text='Elevation in meters')),
                ('country', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SynopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField()),
                ('level', models.CharField(choices=[('SURFACE', 'Surface'), ('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], default='SURFACE', max_length=10)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in knots', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in °C', null=True)),
                ('dew_point', models.FloatField(blank=True, help_text='Dew point in °C', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='Pressure in hPa', null=True)),
                ('pressure_tendency', models.IntegerField(blank=True, help_text='Pressure tendency code', null=True)),
                ('pressure_change', models.FloatField(blank=True, help_text='Pressure change in hPa/3h', null=True)),
                ('cloud_cover', models.IntegerField(blank=True, help_text='Cloud cover in oktas', null=True)),
                ('cloud_base', models.IntegerField(blank=True, help_text='Cloud base height in feet', null=True)),
                ('visibility', models.FloatField(blank=True, help_text='Visibility in km', null=True)),
                ('weather', models.CharField(blank=True, help_text='Current weather (WMO code or description)', max_length=50, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.weatherstation')),
            ],
            options={
                'indexes': [models.Index(fields=['observation_time'], name='analysis_sy_observa_8afe25_idx'), models.Index(fields=['level'], name='analysis_sy_level_d53f86_idx')],
                'unique_together': {('station', 'observation_time', 'level')},
            },
        ),
    ]
