# Generated by Django 5.2 on 2025-04-26 13:07

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('observation_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['level', 'observation_time'], name='analysis_gr_level_ccf130_idx')],
            },
        ),
    ]
