# Generated by Django 5.2 on 2025-04-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_griddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isobar',
            name='level',
            field=models.CharField(choices=[('SURFACE', 'Surface'), ('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], default='SURFACE', max_length=10),
        ),
    ]
