# Generated by Django 5.2 on 2025-05-12 08:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_isobar_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='griddata',
            name='pressure',
            field=models.FloatField(default=1000, help_text='Pressure in hPa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='griddata',
            name='temperature',
            field=models.FloatField(default=1000, help_text='Temperature in °C'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='griddata',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
