# Generated by Django 5.2 on 2025-06-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_griddata_pressure_griddata_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synopreport',
            name='cloud_base',
        ),
        migrations.RemoveField(
            model_name='synopreport',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='synopreport',
            name='weather',
        ),
        migrations.AddField(
            model_name='synopreport',
            name='cloud_high_type',
            field=models.CharField(blank=True, help_text='High cloud type (WMO code)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='cloud_low_type',
            field=models.CharField(blank=True, help_text='Low cloud type (WMO code)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='cloud_mid_type',
            field=models.CharField(blank=True, help_text='Mid cloud type (WMO code)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='max_temperature',
            field=models.FloatField(blank=True, help_text='Maximum temperature (°C)', null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='min_temperature',
            field=models.FloatField(blank=True, help_text='Minimum temperature (°C)', null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='precipitation',
            field=models.FloatField(blank=True, help_text='Precipitation (last period, mm)', null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='precipitation_24h',
            field=models.FloatField(blank=True, help_text='24-hour precipitation (mm)', null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='sea_level_pressure',
            field=models.FloatField(blank=True, help_text='Sea level pressure in hPa', null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='station_pressure',
            field=models.FloatField(blank=True, help_text='Station pressure in hPa', null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='weather_past',
            field=models.CharField(blank=True, help_text='Past weather code', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='synopreport',
            name='weather_present',
            field=models.CharField(blank=True, help_text='Present weather code', max_length=2, null=True),
        ),
    ]
