# Generated by Django 5.2.3 on 2025-07-07 02:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_synopreport_cloud_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpperAirIsobar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(help_text='Pressure in hPa')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('level', models.CharField(choices=[('SURFACE', 'Surface'), ('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], default='SURFACE', max_length=10)),
                ('observation_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpperAirIsotherm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('level', models.CharField(choices=[('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], max_length=10)),
                ('observation_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpperAirPressureCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_type', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low')], max_length=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('pressure', models.FloatField(help_text='Pressure in hPa')),
                ('level', models.CharField(choices=[('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], max_length=10)),
                ('observation_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpperAirWeatherStation',
            fields=[
                ('station_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('elevation', models.FloatField(help_text='Elevation in meters')),
                ('country', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpperAirSynopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField()),
                ('level', models.CharField(choices=[('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], default='800HPA', max_length=10)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in knots', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in °C', null=True)),
                ('dew_point', models.FloatField(blank=True, help_text='Dew point in °C', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='pressure in hPa', null=True)),
                ('height', models.FloatField(blank=True, help_text='Pressure height in hPa', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.upperairweatherstation')),
            ],
            options={
                'indexes': [models.Index(fields=['observation_time'], name='analysis_up_observa_26a9c4_idx'), models.Index(fields=['level'], name='analysis_up_level_e8ab87_idx')],
                'unique_together': {('station', 'observation_time', 'level')},
            },
        ),
    ]
