# Generated by Django 5.2.3 on 2025-07-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_upperairisobar_upperairisotherm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upperairsynopreport',
            name='level',
            field=models.CharField(choices=[('850HPA', '850 hPa'), ('700HPA', '700 hPa'), ('500HPA', '500 hPa'), ('200HPA', '200 hPa')], default='850HPA', max_length=10),
        ),
    ]
